---
title: "Indian Food Cookbook"
author: "Emily Huie"
date: "2/10/2022"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(naniar)

```

1. Loading the data file.
```{r}
indian_food<- read_csv(here("group_project", "indian_food.csv"))%>% clean_names()
```
2. Structure of the data. 

```{r}
indian_food
```
```{r}
summary(indian_food)
```

_Changing -1 to NA_
```{r}
indian_food<-indian_food%>%
  na_if("-1")
```
```{r}
summary(indian_food)
```
3. Names of the Variables
```{r}
names(indian_food)
```

```{r}
glimpse(indian_food)
```
_How much NA?_
```{r}
naniar::miss_var_summary(indian_food)
```


_Split Ingredients Into Their Own Row_
```{r}
indian_food<-indian_food%>%
  mutate_all(tolower)%>%
  transform(ingredients=str_split(ingredients,","))%>%
  unnest(ingredients)
indian_food

```
_Ingredients_
```{r}
indian_food%>%
  group_by(ingredients)%>%
  summarise(n_recipes=n_distinct(name))
```
```{r}
indian_food%>%
  group_by(name)%>%
  summarise(n_ingredients=n_distinct(ingredients))
```

```{r}
indian_food%>%
  group_by(diet)%>%
  summarise(n_recipe=n_distinct(name))
```

```{r}
#4. state --> what ingredient is used the most for each state?
#5. % of ingridient that contains what recipe
#9. in data, what percent of dishes are main courses, which are snakcks...
```

